# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1txCzmfxvOPentO6j3kST6HOFqThUdybF
"""

# Instala la librería si es necesario (solo descomenta si no está instalada)
# !pip install yfinance

import yfinance as yf
import pandas as pd
from datetime import datetime

# 2. Obtener los datos del S&P 500 (^GSPC)
ticker_sp500 = '^GSPC'
start_date = '2020-01-01'
end_date = datetime.now().strftime('%Y-%m-%d') # Fecha de hoy

sp500_data = yf.download(ticker_sp500, start=start_date, end=end_date)

print("--- Datos Históricos del S&P 500 ---")
print(sp500_data.head())

"""# **Analisis del rendimiento del mercado en ls ùltimos 5 años**

Vemos como el S&P 500 venìa incrementando su valor hasta que el año 2022,sin embargo  presenta  una fuerte caida ese mismo año.

Posteriormente se inicia una recueperaciòn del indice y hasta el dìa de hoy se mantiene en maximos historicos.
"""

import yfinance as yf
import matplotlib.pyplot as plt
from datetime import datetime

# --- 1. Descargar datos históricos del S&P 500 ---
ticker_sp500 = '^GSPC'
start_date = '2020-01-01'
end_date = datetime.now().strftime('%Y-%m-%d')  # fecha de hoy

sp500_data = yf.download(ticker_sp500, start=start_date, end=end_date)

print("--- Datos Históricos del S&P 500 ---")
print(sp500_data.head())

# --- 2. Graficar evolución del índice ---
plt.figure(figsize=(12,6))
plt.plot(sp500_data.index, sp500_data['Close'], label='S&P 500', color='blue')
plt.title("Evolución del S&P 500 desde 2020", fontsize=14)
plt.xlabel("Fecha")
plt.ylabel("Precio de Cierre (USD)")
plt.legend()
plt.grid(True, linestyle="--", alpha=0.6)
plt.show()

# 2. Obtener los datos del S&P 500 (^GSPC)
ticker_sp500 = '^GSPC'
start_date = '2020-01-04'
end_date = datetime.now().strftime('2025-12-19') # Fecha de hoy

sp500_data = yf.download(ticker_sp500, start=start_date, end=end_date)

print("--- Datos Históricos del S&P 500 ---")
print(sp500_data.head())

import matplotlib.pyplot as plt

# Crear el gráfico de línea para el precio de cierre
plt.figure(figsize=(12, 6))
plt.plot(sp500_data.index, sp500_data['Close'])
plt.title('Precio de Cierre del S&P 500')
plt.xlabel('Fecha')
plt.ylabel('Precio de Cierre')
plt.grid(True)
plt.show()

"""**Comparaciòn del indicec completo vs el mercado de energìa**

Vemos que en la escala actual no se puede realizar un anàlisis adecuado.
"""

# Ruta del archivo en tu Google Drive
FILE_PATHI = '/content/drive/MyDrive/Boot Camp/Datos 3/sp500_index.csv'

# Leer el archivo CSV
df = pd.read_csv(FILE_PATHI)

# Mostrar las primeras filas
print("=== Primeras 5 filas ===")
display(df.head(500))

# 3. Obtener datos históricos del sector Energía (usando el ETF XLE)
ticker_energia = 'XLE' # Energy Select Sector SPDR Fund (ETF del sector Energía del S&P 500)

energia_data = yf.download(ticker_energia, start=start_date, end=end_date)

print("\n--- Datos Históricos del Sector Energía (XLE) ---")
print(energia_data.head())

# Comparar el S&P 500 y el Sector Energía (XLE) en un mismo gráfico

plt.figure(figsize=(14, 7))

plt.plot(sp500_data.index, sp500_data['Close'], label='S&P 500 (^GSPC)')
plt.plot(energia_data.index, energia_data['Close'], label='Sector Energía (XLE)')

plt.title('Comparación del Precio de Cierre: S&P 500 vs Sector Energía (XLE)')
plt.xlabel('Fecha')
plt.ylabel('Precio de Cierre')
plt.legend()
plt.grid(True)
plt.show()

"""# Task
Comparar los rendimientos porcentuales del S&P 500 y el sector energético.

## Calculate daily returns

### Subtask:
Calcular el cambio porcentual diario del precio de cierre de los marcos de datos del S&P 500 y del sector energético.

**Reasoning**:
Calculate the daily percentage change for the 'Close' price of both the S&P 500 and Energy sector dataframes and store them in new columns.
"""

sp500_data['Daily_Return_SP500'] = sp500_data['Close'].pct_change()
energia_data['Daily_Return_Energia'] = energia_data['Close'].pct_change()

print("--- S&P 500 Data with Daily Returns ---")
print(sp500_data.head())

print("\n--- Energia Data with Daily Returns ---")
print(energia_data.head())

"""## Calculate daily returns

### Subtask:
Calculate the daily percentage change for the 'Close' price of both the S&P 500 and Energy sector dataframes.

**Reasoning**:
Calculate the daily percentage change for the 'Close' price of both the S&P 500 and Energy sector dataframes and store them in new columns.
"""

sp500_data['Daily_Return_SP500'] = sp500_data['Close'].pct_change()
energia_data['Daily_Return_Energia'] = energia_data['Close'].pct_change()

print("--- S&P 500 Data with Daily Returns ---")
print(sp500_data.head())

print("\n--- Energia Data with Daily Returns ---")
print(energia_data.head())

"""## Calculate cumulative returns

### Subtask:
Calculate the cumulative percentage returns based on the daily returns.

**Reasoning**:
Calculate the cumulative returns for both the S&P 500 and the Energy sector and display the updated dataframes.
"""

sp500_data['Cumulative_Return_SP500'] = (1 + sp500_data['Daily_Return_SP500']).cumprod()
energia_data['Cumulative_Return_Energia'] = (1 + energia_data['Daily_Return_Energia']).cumprod()

print("--- S&P 500 Data with Cumulative Returns ---")
display(sp500_data.head())

print("\n--- Energia Data with Cumulative Returns ---")
display(energia_data.head())

"""## Visualize cumulative returns

### Subtask:
Plot the cumulative percentage returns of both the S&P 500 and Energy sector on the same graph.

# Sección nueva

**Indice vs sector energìa**:
Grafica de la evoluciòn del indice comparado especificamente con el sector energìa en los ultimos años
"""

# Create a figure and axes for the plot
plt.figure(figsize=(14, 7))

# Plot the cumulative return of the S&P 500
plt.plot(sp500_data.index, sp500_data['Cumulative_Return_SP500'], label='S&P 500 (^GSPC) Cumulative Return')

# Plot the cumulative return of the Energy sector
plt.plot(energia_data.index, energia_data['Cumulative_Return_Energia'], label='Sector Energía (XLE) Cumulative Return')

# Add title and labels
plt.title('Comparación del Rendimiento Acumulado: S&P 500 vs Sector Energía (XLE)')
plt.xlabel('Fecha')
plt.ylabel('Rendimiento Acumulado')

# Add legend and grid
plt.legend()
plt.grid(True)

# Display the plot
plt.show()

"""# **Factores Globales que Influyeron en el Comportamiento de los Mercados en 2022**

El marcado contraste en el rendimiento del S&P 500 general y su sector de energía estuvo fuertemente influenciado por una serie de eventos y cambios en el ámbito político, económico y social global en 2022:

# 1. Guerra en Ucrania y Crisis Energética Global:
I**nvasión Rusa a Ucrania** (febrero de 2022): Este evento generó una enorme incertidumbre geopolítica y una disrupción en el suministro energético global. Rusia es uno de los mayores exportadores mundiales de combustibles fósiles (petróleo y gas).


**Impacto en la Energía**: El aumento en los precios de las materias primas energéticas se tradujo directamente en ganancias e ingresos extraordinarios para las empresas del sector energético (como Exxon Mobil y Chevron), impulsando fuertemente el S&P 500 Energy.


**Cambio en el Gasto:** Los consumidores se vieron obligados a priorizar el gasto esencial (como la energía y los alimentos), lo que impactó las ganancias de las empresas en sectores de gasto discrecional y de consumo, contribuyendo a la caída de las acciones en el S&P 500 general.

En resumen, la guerra en Ucrania y la consiguiente crisis energética impulsaron los precios del petróleo, beneficiando al sector de Energía. Simultáneamente, la necesidad de controlar la alta inflación llevó a la subida de tasas de interés por parte de la Fed, lo que penalizó fuertemente a las empresas de crecimiento y al mercado en general, causando la caída del S&P 500.


"""

